apiVersion: v1  # API version for ConfigMap.
kind: ConfigMap  # The type of resource.
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-controller  # Name of the ConfigMap.
  labels:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}  # Labels for the ConfigMap.
    app.kubernetes.io/instance: {{ .Release.Name }}  # Helm release name.
data:
  use-forwarded-headers: "{{ .Values.controller.config.use-forwarded-headers }}"  # Config setting for forwarding headers.
