apiVersion: apps/v1  # API version for Deployment.
kind: Deployment  # The type of resource.
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-controller  # Name of the deployment.
  labels:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}  # Labels for the deployment.
    app.kubernetes.io/instance: {{ .Release.Name }}  # Helm release name.
spec:
  replicas: {{ .Values.controller.replicaCount }}  # Number of replicas.
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}  # Selector labels.
      app.kubernetes.io/instance: {{ .Release.Name }}  # Helm release name.
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}  # Labels for the pods.
        app.kubernetes.io/instance: {{ .Release.Name }}  # Helm release name.
    spec:
      containers:
        - name: controller  # Container name.
          image: "k8s.gcr.io/ingress-nginx/controller:v1.0.0"  # Image for the NGINX controller.
          args:
            - /nginx-ingress-controller  # Command to start the controller.
            - --configmap=$(POD_NAMESPACE)/{{ include "ingress-nginx.fullname" . }}-controller  # ConfigMap for configuration.
            - --publish-service=$(POD_NAMESPACE)/{{ include "ingress-nginx.fullname" . }}-controller  # Service to publish the IP.
          env:
            - name: POD_NAMESPACE  # Environment variable for the pod's namespace.
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace  # Get the namespace from the pod metadata.
