apiVersion: networking.k8s.io/v1  # API version for IngressClass.
kind: IngressClass  # The type of resource.
metadata:
  name: nginx  # Name of the IngressClass.
  labels:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}  # Labels for the IngressClass.
    app.kubernetes.io/instance: {{ .Release.Name }}  # Helm release name.
spec:
  controller: k8s.io/ingress-nginx  # Specifies the controller for the IngressClass.
