apiVersion: v1  # API version for Service.
kind: Service  # The type of resource.
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-controller  # Name of the service.
  labels:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}  # Labels for the service.
    app.kubernetes.io/instance: {{ .Release.Name }}  # Helm release name.
spec:
  type: {{ .Values.controller.service.type }}  # Type of service (ClusterIP, NodePort, LoadBalancer).
  loadBalancerIP: {{ .Values.controller.service.loadBalancerIP }}  # Static IP for LoadBalancer.
  ports:
    - port: 80  # Port for HTTP traffic.
      targetPort: http  # Target port for the HTTP service.
    - port: 443  # Port for HTTPS traffic.
      targetPort: https  # Target port for the HTTPS service.
  selector:
    app.kubernetes.io/name: {{ include "ingress-nginx.name" . }}  # Selector labels for the pods.
    app.kubernetes.io/instance: {{ .Release.Name }}  # Helm release name.
