apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-dns.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "external-dns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "external-dns.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "external-dns.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: external-dns
          image: "k8s.gcr.io/external-dns/external-dns:v0.10.1"
          args:
            - --source=service
            - --source=ingress
            - --provider={{ .Values.provider }}
            - --google-project={{ .Values.google.project }}
            - --domain-filter={{ .Values.domainFilters | join "," }}
            - --policy={{ .Values.policy }}
            - --txt-owner-id={{ .Values.txtOwnerId }}
            - --log-level={{ .Values.logLevel }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secrets/credentials.json
          volumeMounts:
            - name: google-cloud-key
              mountPath: /etc/secrets/
              readOnly: true
      volumes:
        - name: google-cloud-key
          secret:
            secretName: external-dns-gcp-sa
