apiVersion: v1  # API version for Service.
kind: Service  # The type of resource.
metadata:
  name: {{ include "cert-manager.fullname" . }}  # Name of the service.
  labels:
    app.kubernetes.io/name: {{ include "cert-manager.name" . }}  # Labels for the service.
    app.kubernetes.io/instance: {{ .Release.Name }}  # Helm release name.
spec:
  ports:
    - port: 9402  # Metrics port.
      targetPort: 9402  # Target port in the container.
  selector:
    app.kubernetes.io/name: {{ include "cert-manager.name" . }}  # Selector labels for the pods.
    app.kubernetes.io/instance: {{ .Release.Name }}  # Helm release name.
