apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-cd.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
